import { Colors } from '@/styles/colors';
import fontFamily from '@/styles/fontFamily';
import { moderateScale } from '@/styles/scaling';
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.background,
    },
    topBackground: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: moderateScale(200),
        backgroundColor: '#F1DFF2',
    },
    scroll: {
        flex: 1,
    },
    contentContainer: {
        paddingHorizontal: moderateScale(8),
        paddingBottom: moderateScale(20),
    },
    avatarWrap: {
        width: moderateScale(102),
        height: moderateScale(102),
        borderRadius: moderateScale(51),
        alignSelf: 'center',
        marginTop: moderateScale(6),
        marginBottom: moderateScale(-20),
        backgroundColor: Colors.white,
        padding: moderateScale(2),
        zIndex: 2,
        shadowColor: Colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 6,
        elevation: 3,
    },
    avatar: {
        width: '100%',
        height: '100%',
        borderRadius: moderateScale(50),
    },
    mainCard: {
        backgroundColor: Colors.surface,
        borderRadius: moderateScale(22),
        paddingHorizontal: moderateScale(14),
        paddingTop: moderateScale(34),
        paddingBottom: moderateScale(16),
        shadowColor: Colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    nameText: {
        textAlign: 'center',
        color: Colors.gray600,
        fontFamily: fontFamily.bold,
        fontSize: moderateScale(20 / 1.2),
        marginBottom: moderateScale(2),
    },
    emailText: {
        textAlign: 'center',
        color: Colors.brandSalmon,
        fontFamily: fontFamily.regular,
        fontSize: moderateScale(15 / 1.1),
        marginBottom: moderateScale(2),
    },
    birthText: {
        textAlign: 'center',
        color: Colors.brandPurple,
        fontFamily: fontFamily.regular,
        fontSize: moderateScale(15 / 1.1),
        marginBottom: moderateScale(16),
    },
    sectionTitle: {
        color: Colors.gray700,
        fontFamily: fontFamily.bold,
        fontSize: moderateScale(18 / 1.1),
        marginBottom: moderateScale(10),
        marginTop: moderateScale(4),
    },
    metricsRow: {
        flexDirection: 'row',
        gap: moderateScale(8),
        marginBottom: moderateScale(14),
    },
    metricCard: {
        flex: 1,
        backgroundColor: '#FBEDED',
        borderRadius: moderateScale(10),
        paddingVertical: moderateScale(10),
        alignItems: 'center',
    },
    metricValue: {
        color: '#B96A61',
        fontFamily: fontFamily.bold,
        fontSize: moderateScale(16),
        marginBottom: moderateScale(4),
        textAlign: 'center',
    },
    metricLabel: {
        color: Colors.gray600,
        fontFamily: fontFamily.regular,
        fontSize: moderateScale(14 / 1.15),
        textAlign: 'center',
    },
    planCard: {
        backgroundColor: Colors.surface,
        borderRadius: moderateScale(12),
        borderWidth: 1,
        borderColor: Colors.gray100,
        padding: moderateScale(10),
        marginBottom: moderateScale(14),
        shadowColor: Colors.black,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 1,
    },
    planTopRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: moderateScale(10),
    },
    planTitle: {
        color: Colors.gray700,
        fontFamily: fontFamily.bold,
        fontSize: moderateScale(16 / 1.1),
    },
    planSubText: {
        color: Colors.gray500,
        fontFamily: fontFamily.regular,
        fontSize: moderateScale(13),
    },
    planPrice: {
        color: Colors.gray700,
        fontFamily: fontFamily.bold,
        fontSize: moderateScale(16 / 1.1),
    },
    planButton: {
        width: moderateScale(160),
        alignSelf: 'flex-start',
        borderRadius: moderateScale(20),
    },
    planButtonText: {
        color: Colors.white,
        fontFamily: fontFamily.bold,
        fontSize: moderateScale(15 / 1.1),
    },
    settingsList: {
        gap: moderateScale(10),
    },
    settingItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.surface,
        borderRadius: moderateScale(12),
        borderWidth: 1,
        borderColor: Colors.gray100,
        paddingVertical: moderateScale(14),
        paddingHorizontal: moderateScale(10),
    },
    settingIconWrap: {
        width: moderateScale(34),
        height: moderateScale(34),
        borderRadius: moderateScale(7),
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: moderateScale(10),
    },
    settingTitle: {
        flex: 1,
        color: Colors.gray700,
        fontFamily: fontFamily.regular,
        fontSize: moderateScale(17 / 1.2),
    },
    logoutIconWrap: {
        alignItems: 'center',
        marginBottom: moderateScale(8),
    },
    logoutIconCircle: {
        width: moderateScale(92),
        height: moderateScale(92),
        borderRadius: moderateScale(46),
        backgroundColor: Colors.brandPurple,
        alignItems: 'center',
        justifyContent: 'center',
    },
    logoutTitle: {
        color: Colors.gray700,
        fontFamily: fontFamily.bold,
        fontSize: moderateScale(20 / 1.2),
        textAlign: 'center',
        marginBottom: moderateScale(16),
        paddingHorizontal: moderateScale(8),
    },
    logoutActionsRow: {
        flexDirection: 'row',
        gap: moderateScale(10),
        width: '100%',
        marginTop: moderateScale(4),
    },
    logoutActionButton: {
        flex: 1,
        borderRadius: moderateScale(22),
    },
    logoutNoText: {
        color: Colors.gray700,
        fontFamily: fontFamily.bold,
    },
    deactivateTitle: {
        color: Colors.gray700,
        fontFamily: fontFamily.bold,
        fontSize: moderateScale(33 / 1.7),
        lineHeight: moderateScale(44 / 1.7),
        textAlign: 'center',
        marginBottom: moderateScale(14),
        paddingHorizontal: moderateScale(12),
    },
    deactivateMessage: {
        color: '#FF4A4A',
        fontFamily: fontFamily.regular,
        fontSize: moderateScale(27 / 1.7),
        lineHeight: moderateScale(40 / 1.7),
        textAlign: 'left',
        marginBottom: moderateScale(20),
    },
    deactivateButton: {
        width: '100%',
        borderRadius: moderateScale(28),
    },
});

export default styles;
