import * as Screens from '@/screens';
const routes = {
  auth: {
    login: 'Login',
    forgot: 'Forgot',
    onboarding: 'Onboarding',
    register: 'Register',
    healthConsent: 'HealthConsent',
    dateOfBirth: 'DateOfBirth',
    height: 'Height',
    weight: 'Weight',
    healthPreferences: 'HealthPreferences',
  },
  main: {
    profile: 'Profile',
    settings: 'Settings',
    userProfile: 'UserProfile',
    chatAi: 'ChatAi',
    shop: 'Shop',
    categories: 'Categories',
    myOrders: 'MyOrders',
    subscription: 'Subscription',
    mySessions: 'MySessions',    ourCollaboration: 'OurCollaboration',
    insurance: 'Insurance',
    manageSubscriptions: 'ManageSubscriptions',
    billingHistory: 'BillingHistory',
    paymentMethod: 'PaymentMethod',
    help: 'Help',
    support: 'Support',
    logPeriod: 'LogPeriod',
    ovulationFertility: 'OvulationFertility',
    notification: 'Notification',
    logSymptoms: 'LogSymptoms',
    cycleHistory: 'CycleHistory',
    insightsThreads: 'InsightsThreads',
    reminderAlert: 'ReminderAlert',
    aiChatScreen: 'AiChatScreen',
    categoryProducts: 'CategoryProducts',
    productDetails: 'ProductDetails',
    cart: 'Cart',
    ratingReview: 'RatingReview',
    checkout: 'Checkout',
    shippingAddress: 'ShippingAddress',
    addShippingAddress: 'AddShippingAddress',
    cardDetails: 'CardDetails',
    enterPin: 'EnterPin',
    requestAppointment: 'RequestAppointment',
    requestAquote: 'RequestAquote',
    applicationStatus: 'ApplicationStatus',
    orderDetails: 'OrderDetails',
    writeRatingReview: 'WriteRatingReview',
},
  tab: {
    home: 'Home',
    cycleOverview: 'CycleOverview',
    chatAi: 'ChatAi',
    shop: 'Shop',
    categories: 'Categories',
  },
  navigator: {
    auth: 'Auth',
    main: 'Main',
    tab: 'Tabs',
  },
} as const;
export const authRoutes = {
  [routes.auth.login]: Screens.Login,
  [routes.auth.forgot]: Screens.Forgot,
  [routes.auth.onboarding]: Screens.Onboard,
  [routes.auth.register]: Screens.Register,
  [routes.auth.healthConsent]: Screens.HealthConsent,
  [routes.auth.dateOfBirth]: Screens.DateOfBirth,
  [routes.auth.height]: Screens.Height,
  [routes.auth.weight]: Screens.Weight,
  [routes.auth.healthPreferences]: Screens.HealthPreferences,
};
export const tabRoutes = {
  [routes.tab.cycleOverview]: Screens.CycleOverview,
  [routes.tab.chatAi]: Screens.ChatAi,
  [routes.tab.shop]: Screens.Shop,
  [routes.tab.categories]: Screens.Categories,
  [routes.tab.home]: Screens.Home,
};
export const mainRoutes = {
  // Add other main stack screens here that are not in tabs,
  [routes.main.chatAi]: Screens.ChatAi,
  [routes.main.shop]: Screens.Shop,
  [routes.main.categories]: Screens.Categories,
  [routes.main.myOrders]: Screens.MyOrders,
  [routes.main.subscription]: Screens.Subscription,
  [routes.main.mySessions]: Screens.MySessions,  [routes.main.ourCollaboration]: Screens.OurCollaboration,
  [routes.main.insurance]: Screens.Insurance,
  [routes.main.manageSubscriptions]: Screens.ManageSubscriptions,
  [routes.main.billingHistory]: Screens.BillingHistory,
  [routes.main.paymentMethod]: Screens.PaymentMethod,
  [routes.main.help]: Screens.Help,
  [routes.main.support]: Screens.Support,
  [routes.main.logPeriod]: Screens.LogPeriod,
  [routes.main.ovulationFertility]: Screens.OvulationFertility,
  [routes.main.notification]: Screens.Notification,
  [routes.main.logSymptoms]: Screens.LogSymptoms,
  [routes.main.cycleHistory]: Screens.CycleHistory,
  [routes.main.insightsThreads]: Screens.InsightsThreads,
  [routes.main.reminderAlert]: Screens.ReminderAlert,
  [routes.main.aiChatScreen]: Screens.AiChatScreen,
  [routes.main.categoryProducts]: Screens.CategoryProducts,
  [routes.main.productDetails]: Screens.ProductDetails,
  [routes.main.cart]: Screens.Cart,
  [routes.main.ratingReview]: Screens.RatingReview,
  [routes.main.checkout]: Screens.Checkout,
  [routes.main.shippingAddress]: Screens.ShippingAddress,
  [routes.main.addShippingAddress]: Screens.AddShippingAddress,
  [routes.main.cardDetails]: Screens.CardDetails,
  [routes.main.enterPin]: Screens.EnterPin,
  [routes.main.requestAppointment]: Screens.RequestAppointment,
  [routes.main.requestAquote]: Screens.RequestAquote,
  [routes.main.applicationStatus]: Screens.ApplicationStatus,
  [routes.main.orderDetails]: Screens.OrderDetails,
  [routes.main.writeRatingReview]: Screens.WriteRatingReview,
};
export default routes;
