import * as Screens from '@/screens';
const routes = {
  auth: {
    login: 'Login',
    forgot: 'Forgot',
    onboarding: 'Onboarding',
    register: 'Register',
    healthConsent: 'HealthConsent',
    dateOfBirth: 'DateOfBirth',
    height: 'Height',
    weight: 'Weight',
    healthPreferences: 'HealthPreferences',
  },
  main: {
    profile: 'Profile',
    settings: 'Settings',
    userProfile: 'UserProfile',
    chatAi: 'ChatAi',
    shop: 'Shop',
    categories: 'Categories',
    myOrders: 'MyOrders',
    subscription: 'Subscription',
    mySessions: 'MySessions',    ourCollaboration: 'OurCollaboration',
    insurance: 'Insurance',
    manageSubscriptions: 'ManageSubscriptions',
    billingHistory: 'BillingHistory',
    paymentMethod: 'PaymentMethod',
    help: 'Help',
    support: 'Support',
},
  tab: {
    home: 'Home',
    cycleOverview: 'CycleOverview',
    chatAi: 'ChatAi',
    shop: 'Shop',
    categories: 'Categories',
  },
  navigator: {
    auth: 'Auth',
    main: 'Main',
    tab: 'Tabs',
  },
} as const;
export const authRoutes = {
  [routes.auth.login]: Screens.Login,
  [routes.auth.forgot]: Screens.Forgot,
  [routes.auth.onboarding]: Screens.Onboard,
  [routes.auth.register]: Screens.Register,
  [routes.auth.healthConsent]: Screens.HealthConsent,
  [routes.auth.dateOfBirth]: Screens.DateOfBirth,
  [routes.auth.height]: Screens.Height,
  [routes.auth.weight]: Screens.Weight,
  [routes.auth.healthPreferences]: Screens.HealthPreferences,
};
export const tabRoutes = {
  [routes.tab.cycleOverview]: Screens.CycleOverview,
  [routes.tab.chatAi]: Screens.ChatAi,
  [routes.tab.shop]: Screens.Shop,
  [routes.tab.categories]: Screens.Categories,
  [routes.tab.home]: Screens.Home,
};
export const mainRoutes = {
  // Add other main stack screens here that are not in tabs,
  [routes.main.chatAi]: Screens.ChatAi,
  [routes.main.shop]: Screens.Shop,
  [routes.main.categories]: Screens.Categories,
  [routes.main.myOrders]: Screens.MyOrders,
  [routes.main.subscription]: Screens.Subscription,
  [routes.main.mySessions]: Screens.MySessions,  [routes.main.ourCollaboration]: Screens.OurCollaboration,
  [routes.main.insurance]: Screens.Insurance,
  [routes.main.manageSubscriptions]: Screens.ManageSubscriptions,
  [routes.main.billingHistory]: Screens.BillingHistory,
  [routes.main.paymentMethod]: Screens.PaymentMethod,
  [routes.main.help]: Screens.Help,
  [routes.main.support]: Screens.Support,
};
export default routes;
